
post http://localhost:3000/api/nimiolemassa
Content-Type: application/json

{
    "name":"XYZ"
}

###
POST http://localhost:3000/api/nimiolemassa
Content-Type: application/json

{
    "name":"ABC"
}

###

get http://localhost:3000/api/nxt
###

get http://localhost:3000/api/ohjelmat
###

get http://localhost:3000/api/ohjelmat/333
###


post http://localhost:3000/api/tallenna/666
Content-Type: application/json

{
    "nimi":"wwdfsdfsdfsdfweg",
    "xml": "<xml xmlns='http://www.w3.org/1999/xhtml' />"
}
###






get http://localhost:3000/api/testDone


####




get http://localhost:3000/api/true/12342
###






###

###
get http://localhost:3000/savetest

###



########################################################################33

get http://localhost:3000/api/testFlag
###

get http://localhost:3000/api/XMLstorage
###

get http://localhost:3000/api/onkoTallennusJoOlemassa/XYZ
###

get http://localhost:3000/api/onkoTallennusJoOlemassa/XYZZ
###

get http://localhost:3000/api/ohjelmat
###

post http://localhost:3000/api/saveXML3/123
Content-Type: application/json

{
    "nimi":"joo",
    "xml": "<xml xmlns='http://www.w3.org/1999/xhtml'>"
}




get http://localhost:3000/api/testFlag
###

get http://localhost:3000/api/XMLstorage
###

get http://localhost:3000/api/onkoTallennusJoOlemassa/XYZ
###

get http://localhost:3000/api/onkoTallennusJoOlemassa/XYZZ
###






























get http://localhost:3000


###

get http://localhost:3000/api/nextCommand



###


post http://localhost:3000/api/saveXML
Content-Type: application/json

{
    "xml": "<xml xmlns='http://www.w3.org/1999/xhtml'>"
}

###


post http://localhost:3000/api/saveXML
Content-Type: application/json

{
    "test1": "123",
    "test2": "456"
}

###


post http://localhost:3000/savetest
Content-Type: application/json

{
    "test1": "123",
    "test2": "456"
}

###

###
get http://localhost:3000/savetest

###

